# Generated by Django 3.2.3 on 2021-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210704_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.FileField(default='', upload_to='shop/images/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
